[package]
name = "pewter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.2"
bitflags = "1.3.2"
variant_count = "1.1.0"

[dev-dependencies]
proptest = "1.0.0"
