[package]
name = "pewter-core"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
anyhow = "1.0.103"
arrayvec = "0.7.8"
bitflags = "2.13.0"
crossbeam-channel = "0.5.16"
log = "0.4.33"
rand = { version = "0.9.2", features = ["small_rng"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
tracing = "0.1.44"
variant_count = "1.2.1"

[dev-dependencies]
proptest = "1.11.0"
criterion = "0.8.2"

[build-dependencies]
rand = { version = "0.9.2", features = ["small_rng"] }
anyhow = "1.0.103"

[[bench]]
name = "bench"
harness = false
