[project]
name = "tourney"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chess>=1.11.1",
    "pydantic>=2.9.2",
    "tqdm>=4.66.5",
]

[tool.uv]
dev-dependencies = [
    "ipython>=8.28.0",
]
